### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by kawapure** [VORAPIS/v3#1]
hii :3

**Comment by VORAPIS** [comment]
hii :3
![V3_BIG_LOGO_OWN](https://github.com/VORAPIS/v3/assets/102152194/006f3deb-aea7-498d-a31d-3237e810d86d)

**Comment by VoidedNull** [comment]
hello!

**Comment by CaptainEldeezee** [comment]
Ello!
![mineturt](https://github.com/user-attachments/assets/e29539b4-5d17-4a6c-8f86-70990dfba733)
